# Generated by Django 4.2.28 on 2026-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursematerial_coursefeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked'), ('REMOVED', 'Removed')], default='PENDING', max_length=10),
        ),
    ]
