# Generated by Django 4.2.28 on 2026-03-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrolment_remark_alter_enrolment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['lesson__order', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('image', 'Image'), ('file', 'File')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson'),
        ),
    ]
