# Generated by Django 4.2.28 on 2026-03-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursematerial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
